# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # - board: planck_rev6
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
  # - board: glove80_lh
  # - board: glove80_rh
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
  # - board: eyelash_corne_left
  #   shield: nice_view
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  #   artifact-name: eyelash_corne_studio_left
  # - board: eyelash_corne_right
  #   shield: settings_reset
  # - board: eyelash_corne_left
  #   shield: settings_reset
    #snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: totem_left
    # cmake-args: -DSHIELD=totem_left -DCMAKE_PREFIX_PATH=$PWD/totem/config
  - board: seeeduino_xiao_ble
    shield: totem_right
